before_install:
  - sudo apt-get update -qq || true
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-pl
language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - NMODE=nikola
  - NMODE=flake8
install:
  - "[[ $NMODE == 'nikola' ]] && pip install -r requirements-tests.txt --use-mirrors || true"
  - "[[ $NMODE == 'nikola' ]] && pip install . --use-mirrors || true"
  - "[[ $NMODE == 'flake8' ]] && pip install flake8 --use-mirrors || true"
# We run tests, nikola (to see if the command is executable) and flake8.
script:
  - "[[ $NMODE == 'nikola' ]] && nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy || true"
  - "[[ $NMODE == 'nikola' ]] && nikola help || true"
  - "[[ $NMODE == 'flake8' ]] && flake8 --ignore=E501 . || true"
after_success:
  - "[[ $NMODE == 'nikola' ]] && coveralls || true"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
